# Generated by Django 5.2 on 2025-04-07 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('vegetables', 'Vegetables'), ('fruits', 'Fruits'), ('dairy', 'Dairy'), ('meat', 'Meat'), ('poultry', 'Poultry'), ('fish', 'Fish & Seafood'), ('eggs', 'Eggs'), ('baked', 'Baked Goods'), ('leftovers', 'Leftovers'), ('spreads', 'Spreads & Dips'), ('condiments', 'Condiments & Sauces'), ('beverages', 'Beverages'), ('frozen', 'Frozen Foods'), ('snacks', 'Snacks & Sweets'), ('prepared', 'Prepared Meals'), ('other', 'Other')], max_length=50)),
                ('quantity', models.IntegerField(default=1)),
                ('best_by', models.DateField()),
            ],
        ),
    ]
