# Generated by Django 5.2 on 2025-04-07 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0002_alter_fooditem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='category',
            field=models.CharField(choices=[('vegetables', 'Vegetables'), ('fruits', 'Fruits'), ('dairy', 'Dairy'), ('meat', 'Meat'), ('poultry', 'Poultry'), ('fish', 'Fish & Seafood'), ('eggs', 'Eggs'), ('baked', 'Baked Goods'), ('leftovers', 'Leftovers'), ('spreads', 'Spreads & Dips'), ('condiments', 'Condiments & Sauces'), ('beverages', 'Beverages'), ('frozen', 'Frozen Foods'), ('snacks', 'Snacks & Sweets'), ('prepared', 'Prepared Meals'), ('other', 'Other')], max_length=50),
        ),
    ]
