# Generated by Django 5.2 on 2025-04-07 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0004_fooditem_storage_location_alter_fooditem_best_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='opened',
            field=models.BooleanField(default=False),
        ),
    ]
